export const book = {
  title: "Shadowfang Island",
  tagline: "The guardianship has begun.",
  authors: ["Mohammed Afzal.A", "Mithelesh.S.R"],
  editors: ["Jagannathan", "Siddharth", "Shanker", "Surya"],
  description:
    "Arthur Kingsley and William Ashford uncover a hidden island built to protect advanced ancient technology. When an unknown threat approaches Earth, the two friends must awaken Shadowfang and face the Sentinel of Void.",
};

export const characterIntro = [
  {
    name: "Arthur Kingsley",
    traits: [
      "Intelligent and observant.",
      "Calm under pressure.",
      "A natural strategist.",
      "Drawn to ancient symbols and hidden knowledge.",
    ],
  },
  {
    name: "William Ashford",
    traits: [
      "Arthur Kingsley’ close friend.",
      "Very loyal and brave when needed.",
      "Skilled with machines, tools, and tech.",
      "Quick thinker in tense moments.",
      "The emotional balance to Arthur Kingsley’s seriousness.",
    ],
  },
];

export const chapters = [
  {
    id: 1,
    title: "Shadowfang Island",
    paragraphs: [
      "THE STORY BEGINS HERE",
      "Arthur Kingsley stood on small research, about an island.",
      "THE SHADOWFANG ISLAND",
      "For years, people said this island was only a rumor. It never showed up on maps or in satellite images. Many said that it doesn’t exist. But Arthur Kingsley had found a strange star symbol on an old map — the same symbol he had seen in his dreams.",
      "Which made Arthur Kingsley and William Ashford more curious about the symbol and the place in the old map. They decided to go that place.",
      "When they both reached that place, the tablet stopped working.",
      "William Ashford said. “Even the compass spins non-stop when we come near this island.”",
      "Arthur Kingsley nodded. “It means the island is real and it exists.”",
      "When the fog moved away, the island became clear.",
      "The island looked empty, but the it felt like it was alive.",
      "Their boat reached at Phantom Dock, the only entry point. Fog floated around the wooden dock. The movement Arthur Kingsley stepped onto the dock.",
      "A stone under his foot clicked.",
      "Suddenly, a glowing projection map appeared in front of them. It showed the names of seven places of the island:",
      "• Crown Peak Quarters",
      "• Iron Vault Garage",
      "• The Obsidian Circle",
      "• Black Forge Facility",
      "• The Abyss Cells",
      "• The Titan Treasury",
      "• Phantom Dock",
      "Then new words appeared:",
      "“WELCOME, GUARDIAN. THE ISLAND HAS BEEN WAITING FOR A LONG TIME FOR YOUR ARRIVAL”",
      "William Ashford looked shocked.",
      "“Claim-holder? Who are they talking about? You or me?”",
      "Arthur Kingsley felt a strange pull inside him — like the island already knew him.",
      "Before he speaks, the dock gate opened automatically. They saw a tunnel, lit by blue flames. When they entered the tunnel, the gate closed behind them immediately.",
      "They followed the tunnel until it opened into a huge underground hall. In the center of the hall there was a round platform with the same star symbol Arthur Kingsley had seen in his dreams.",
      "When Arthur Kingsley stepped close, the platform lit up and showed a new projection:",
      "“ONLY THOSE WHO CARRY THE MARK CAN UNLOCK THE SOUL OF SHADOWFANG.”",
      "William Ashford looked at Arthur Kingsley.",
      "“Do you… have a mark?”",
      "Arthur Kingsley saw him with a short crazy smile and he slowly rolled up his sleeve. A faint glowing star-shaped mark was on his arm — something he had since birth.",
      "The moment the mark entered the light, the whole platform moved and another tunnel opened.",
      "They walked into an underground place called The Obsidian Circle. In the centre there was a pedestal holding a black, shiny object. It looked like a stone, but it felt warm, like it was alive.",
      "When Arthur Kingsley reached out there a new projection appeared:",
      "“THE ISLAND IS AN EXAMPL OF KNOWLEDGE. ONLY THE CHOSEN GUARDIAN CAN AWAKEN IT.”",
      "William Ashford whispered, “Chosen guardian? Who?”",
      "Arthur Kingsley touches the black object with fear.",
      "Instantly, visions filled his mind: Shadowfang was once a secret place created to protect very powerful ancient technologies — (energy, inventions, and knowledge) was too advanced for the world in 1830. The builders disappeared, leaving the island asleep, waiting for someone with the mark to wake the island.",
      "Arthur Kingsley opened his eyes, breathing fast and said “This island wasn’t built to hide danger. It was built to protect the world.”",
      "William Ashford asked, “So why is it waking up now?”",
      "The black object glowed and showed a message:",
      "“A GREAT THREAT IS COMING. SHADOWFANG’S SOUL MUST BE ACTIVATED. YOU ARE THE NEXT GUARDIAN.”",
      "The floor moved again, revealing a glowing staircase leading deeper into the island.",
      "Arthur Kingsley and William Ashford walked down together.",
      "At the bottom there was a giant crystal engine that had been sleeping for hundreds of years. When Arthur Kingsley placed the black object into the center of the engine, the whole island shook.",
      "Lights turned on everywhere. Towers activated. Machines woke up. Shadowfang Island, after 200 years, was alive again.",
      "A final message appeared:",
      "“THE GUARDIANSHIP HAS BEGUN.”",
      "Arthur Kingsley looked at William Ashford.",
      "“Looks like we’re not just explorers anymore.”",
      "William Ashford gave a nervous smile.",
      "“Yeah… we just started something huge.”",
      "The ocean outside roared as the entire island powered up."
    ]
  },
  {
    id: 2,
    title: "The Shadow Above the Stars",
    paragraphs: [
      "The island has fully awoken now.",
      "From the top of the mountain to the lowest tunnel, Shadowfang Island started to glow.",
      "Blue lights passed through the rocks like veins. Wind fans started turning, small drones flew out from hidden rooms, and old machines rose up as they had been sleeping for hundreds of years.",
      "Arthur Kingsley and William Ashford were inside the Titan Treasury, watching the big crystal engine shine brighter and brighter.",
      "“Arthur Kingsley… look at this,” William Ashford whispered.",
      "All the hologram screens around them changed. Instead of old records, they now showed live information from the world.",
      "This was the first time the island had scanned Earth since the year 1840.",
      "One screen showed the sky. Another showed paths of satellites. A third showed a red blinking dot far above Earth.",
      "Arthur Kingsley narrowed his eyes. “What is that?”",
      "The island answered with voice:",
      "“UNKNOWN OBJECT APPROACHING EARTH. ARRIVAL IN 69 HOURS. NOT HUMAN.”",
      "William Ashford’s confused. “Not human? You mean… aliens?”",
      "Before Arthur Kingsley answer, the island spoke again:",
      "“OBJECT SEARCHES FOR SHADOWFANG ENERGY. PURPOSE: TO TAKE IT.”",
      "Arthur Kingsley felt his heart beat. “It wants the power of this island…”",
      "“But why now?” William Ashford asked. “This place was hidden for almost two hundred years!”",
      "Arthur Kingsley looked at the crystal engine.",
      "“Maybe when we activated the island… something out they noticed.”",
      "Suddenly, the room shook lightly. A huge new hologram appeared.",
      "It showed a giant dark structure floating in space.",
      "It looked like a sharp piece of broken metal.",
      "Its surface moved like liquid.",
      "It had glowing symbols that kept changing.",
      "It was not a spaceship. Not a rock. Not anything humans had created.",
      "It looked ancient… and dangerous.",
      "The island spoke again:",
      "“THE SENTINEL OF VOID. AN OLD HARVESTER FROM THE OUTER ZONE.”",
      "“Outer zone?” William Ashford asked. “What is that?”",
      "Arthur Kingsley replied quietly, “Probably a part of space human have never reached.”",
      "The hologram zoomed in. As the Sentinel passed in space, stars behind it turned dim, like their light was being sucked away.",
      "“Arthur Kingsley…” William Ashford whispered. “If it can drain stars—”",
      "“Then it can drain this island too,” Arthur Kingsley said softly.",
      "The island showed one last message:",
      "“IF THE SENTINEL REACHES EARTH, SHADOWFANG WILL BE DESTROYED. GUARDIANS MUST BE PREPARED.”",
      "Arthur Kingsley took a deep breath. “We only have 69 hours.”",
      "William Ashford looked around at the glowing tunnels and rooms. “What do we do?”",
      "Lights turned on one by one across all seven places on the island:",
      "• Crown Peak Quarters — the main control room.",
      "• Iron Vault Garage — vehicles and machines.",
      "• The Obsidian Circle — ancient knowledge.",
      "• Black Forge Facility — inventions and tools.",
      "• The Abyss Cells — protection systems.",
      "• Titan Treasury — main power.",
      "• Phantom Dock — travel and access It felt like the island was showing them the way.",
      "Arthur Kingsley said, “If we learn everything we can.”",
      "William Ashford nodded. “And we can use it to stop that thing.”",
      "The two friends stared at the hologram of the Sentinel of Void, still moving closer to Earth — slowly, calmly, and silently.",
      "Arthur Kingsley Gripped his fists.",
      "Shadowfang Island had woken up for a reason.",
      "And now… we got it.",
      "They again saw the hologram closer…",
      "They felt the Sentinel of Void said I am coming to you.",
      "Arthur Kingsley said without hesitation",
      "“I AM WAITING”"
    ]
  },
  {
    id: 3,
    title: "Arthur Kingsley’s Life",
    paragraphs: [
      "There may be many questions in your mind about Arthur Kingsley and the strange events connected to his life.",
      "How did he get the mysterious mark on his body? How did the old map come into his hands? And what made him begin searching for the hidden place mentioned in it?",
      "This chapter will answer all of these questions.",
      "1. How did Arthur Kingsley get the mark on his body?",
      "The builders of Shadowfang Island were none other than the ancestors of Arthur Kingsley. For generations, Arthur’s family carried a mysterious symbol on their bodies. It was not an ordinary mark, but a sign that connected them to the island and its hidden secrets.",
      "As time passed, each new generation continued the search for Shadowfang Island. Many of them spent their entire lives trying to discover its location, but none were successful. Some disappeared during their journeys, while others returned with no answers.",
      "Years later, Arthur Kingsley’s father decided to continue the mission of his ancestors. He was determined to succeed where the others had failed.",
      "After years of searching, collecting clues, and studying old records, he finally managed to discover the possible location of the island. Before leaving on his final journey, he carefully drew a map that showed where Shadowfang Island could be found.",
      "2. How did he get the old map?",
      "Arthur Kingsley’s father eventually reached the island, but he never returned alive. His death remained one of the greatest mysteries in Arthur’s life.",
      "Some days later, his father’s body was found floating in a river that was connected to the ocean surrounding Shadowfang Island. No one knew what had happened to him. There were no clear signs of what caused his death, and no one could explain the terrifying events that took place there.",
      "When the body was brought back, the old map that his father had carried was also recovered. That was how Arthur Kingsley came into possession of the map.",
      "Many people focused only on the death of Arthur’s father. They tried to understand how he died and what danger had taken his life. However, no one paid attention to the location marked on the map or the secrets that it might reveal.",
      "Arthur was still very young when all of this happened. Because of his age, he did not understand the value of the map or the importance of the strange symbol connected to it.",
      "3. What made him search for that place?",
      "Several years later, Arthur grew older and became deeply interested in ancient symbols, lost history, and mysterious legends. He spent much of his time reading books, studying old writings, and researching unusual signs from different civilizations.",
      "During one of his studies, he noticed something shocking. The symbol drawn on the old map was exactly the same as the mark on his body. Even more strangely, it was also the same symbol that appeared repeatedly in his dreams.",
      "This discovery changed everything.",
      "Arthur became obsessed with finding the truth behind the symbol, the hidden island, and the strange connection between his family and Shadowfang Island.",
      "At the same time, he also wanted answers about his father’s death.",
      "The island was no longer just a mystery from the past—it had become the key to understanding his own life."
    ]
  },
  {
    id: 4,
    title: "William Ashford’s Life",
    paragraphs: [
      "There may be many questions in your mind about William Ashford and the events that shaped his life. How did he become connected to Arthur Kingsley? Why does he always stand beside Arthur during dangerous times? And what made him willing to follow Arthur on the journey to Shadowfang Island?",
      "This chapter will answer all of these questions.",
      "1. Who was William Ashford?",
      "William Ashford was born in a small town and lived a simple life with his family. Unlike Arthur Kingsley, William did not come from a bloodline filled with ancient secrets or mysterious marks. His childhood was normal, peaceful, and free from danger.",
      "From a young age, William was known for his intelligence, courage, and loyalty. He was the kind of person who always helped others without expecting anything in return. Even during difficult times, he remained calm and strong.",
      "As he grew older, William became interested in science, survival skills, and exploring unknown places. He enjoyed solving puzzles and learning about hidden mysteries. Though he lived an ordinary life, he always felt that destiny had prepared something greater for him.",
      "2. How did he meet Arthur Kingsley?",
      "William first met Arthur Kingsley during their school years. At first, they were very different from one another. Arthur was quiet, serious, and often lost in thought, while William was friendly, energetic, and easy to talk to.",
      "Despite their differences, they slowly became close friends. William noticed that Arthur often carried pain and unanswered questions inside him.",
      "Arthur trusted very few people, but over time, William became the one person he could rely on.",
      "Their friendship grew stronger through the years. They helped each other during difficult moments and stood together whenever trouble appeared.",
      "William was not just Arthur’s friend— he became like a brother to him.",
      "3. What made him join the search for Shadowfang Island?",
      "One day, Arthur finally revealed the truth about the old map, the strange symbol, and the mysterious death of his father. He told William everything that had been hidden for years.",
      "Most people would have feared such a story and walked away. But William was different. Instead of fear, he felt curiosity and determination.",
      "He believed that Arthur should not face such a dangerous journey alone.",
      "William also wanted to uncover the truth behind the island and the dark secrets surrounding Arthur’s family.",
      "He knew the journey would be filled with danger, but his loyalty to Arthur was stronger than fear. From that moment, William decided to stand beside Arthur no matter what happened.",
      "4. Why was William important to the journey?",
      "William Ashford was more than just a companion. He was the balance Arthur needed. When Arthur became too serious, William gave him hope. When fear surrounded them, William brought courage. When darkness closed in, he reminded Arthur that he was not alone.",
      "His intelligence, bravery, and quick thinking often helped them escape danger. He could solve problems under pressure and stay calm in terrifying situations.",
      "While Arthur carried the bloodline of secrets, William carried the strength of friendship.",
      "That is why William Ashford became an important part of the journey to Shadowfang Island."
    ]
  },
  {
    id: 5,
    title: "The Last Dark Night",
    paragraphs: [
      "1. What happened after they found the island?",
      "After Arthur Kingsley and William Ashford discovered Shadowfang Island.",
      "They understood the Sentinel of Void was not just a normal enemy. It was a giant being filled with darkness and terrible power.",
      "Soon, strange things started happening everywhere. Dark clouds covered the sky, heavy storms came without warning, and people began to feel fear for no reason. Arthur and William understood that something dangerous is happening.",
      "They knew they cannot run away from this problem. If they did nothing, many people might DIE.",
      "2. What did they do after knowing the situation of the problem?",
      "Arthur understood that normal weapons like knives and guns would not be enough to stop the Sentinel of Void. So, they decided to buildup a powerful weapon. To defeat the Sentinel of Void.",
      "William was very talented with machines and tools. He believed that if they worked together, they could build special weapons strong enough to fight against the dark enemy.",
      "Arthur had knowledge about old symbols and hidden powers. William had skill in making machines and inventions. So, they decided to use both knowledge and skill together.",
      "They found an old empty workshop and turned it into their secret place to work.",
      "3. What weapons did they build?",
      "The first weapon they made was called the Dragonflame Greatsword. It was a sword with ancient symbols carved on it. The sword glowed brightly with fire.",
      "Arthur chose to use this sword and practiced with it every day.",
      "The second weapon they built was called the Aetherion Staff. It was a weapon which was cold and could freeze on whom they use.",
      "They also made special weapon called Soul Reaver Scythe. This weapon was made from strong metal mixed with rare stones found on Shadowfang Island. But the movement they both tried to use that weapon, it did not release any energy.",
      "They though it was of no use and they kept it aside. And started practicing with the two weapons.",
      "4. How did they prepare themselves?",
      "Arthur knew that weapons alone were not enough. He trained every day to become stronger and faster.",
      "William trained himself too. He learned fighting skills, and tested every machine many times to make sure nothing would fail in battle.",
      "They worked hard every day and never gave up.",
      "As time passed, they became stronger in body and mind.",
      "5. What happened next?",
      "After they finished their training, the sky above Shadowfang Island became dark again.",
      "Thunder filled the air, and the sea became wild.",
      "Far away, inside the deep darkness, the Sentinel of Void had entered the Earth.",
      "The movement the Sentinel of Void entered the Earth its shape was changed into a fixed shape.",
      "They saw it in the darkness with a torch light.",
      "Arthur Kingsley and William Ashford looked at each other, ready for the battle of LIVE OR DIE"
    ]
  },
  {
    id: 6,
    title: "Knight Ghost Fire",
    paragraphs: [
      "1. How did the battle begin?",
      "Arthur Kingsley and William Ashford stood together. The sky was dark, thunder roared loudly, and the ground shook.",
      "Arthur attacked first with the Dragonflame Greatsword. Flames rose from the sword and struck the enemy, but the Sentinel of Void was too powerful.",
      "William used the Aetherion Staff and sent waves of freezing energy toward the creature. Ice covered its body for a moment, but the enemy broke free with great force.",
      "The battle became harder with every minute.",
      "2. Why were the heroes losing?",
      "No matter how much they attacked, the Sentinel of Void kept growing stronger. Its dark power was endless.",
      "Arthur was thrown to the ground and badly injured. William was struck away and could barely stand.",
      "Their weapons were damaged, and their strength was almost gone.",
      "They realized they were close to defeat.",
      "For the first time, fear entered their hearts.",
      "3. What happened when they feared?",
      "As Arthur and William struggled to stand, drops of their blood fell onto the weapon they had thrown aside earlier — the Soul Reaver Scythe.",
      "The moment their blood touched it, the weapon began to glow with bright energy. The weapon started glowing, and the entire battlefield shook.",
      "Arthur and William understood that the weapon had been waiting for the blood of true warriors.",
      "With their last strength, they lifted the Soul Reaver Scythe together.",
      "Arthur and William combined their remaining power and threw the glowing Soul Reaver Scythe toward the Sentinel of Void.",
      "The weapon flew through the dark sky like lightning in a dark sky. It struck the center of the enemy and released a massive burst of light.",
      "The Sentinel of Void screamed as its dark body cracked apart. Its power shattered into dust, and the darkness around the island disappeared.",
      "At last, the enemy was destroyed.",
      "Arthur and William had won the battle.",
      "4. What truth did Shadowfang Island reveal?",
      "After the battle, Shadowfang Island began to glow with ancient light. A deep voice echoed across the land.",
      "The island revealed the truth about Arthur’s father.",
      "It said that the island could only be fully activated if one life was given as a sacrifice. Arthur’s father had discovered this secret and chose to give his own life so that the island’s power could awaken for the future.",
      "He did not die by accident. He died by choice.",
      "He gave his life so Arthur could one day finish what he started.",
      "Arthur stood in silence, with tears in his eyes. He finally knew the truth about his father."
    ]
  }
];

export const references = [
  'The phrase "I am waiting" is popularly associated with Vijay and is referenced in this work for creative purposes. All rights to the original dialogue and its source material belong to their respective owners.',
  "This book contains references to popular films, including K.G.F: Chapter 1 and K.G.F: Chapter 2. All related trademarks, copyrights, and intellectual property belong to their respective owners."
];


// Images extracted from the original manuscript and placed at the same narrative locations.
export const illustrations = {
  cover: { src: "/images/image1.jpeg", alt: "Original Shadowfang Island cover artwork" },
  backCover: { src: "/images/image23.jpeg", alt: "Original ending artwork" },
  credits: { src: "/images/image22.png", alt: "Original author logo" },
  chapters: {
    1: [
      { after: "Arthur Kingsley stood on small research, about an island.", src: "/images/image2.jpeg", alt: "Shadowfang Island emerging through the storm" },
      { after: "William Ashford looked shocked.", src: "/images/image3.jpeg", alt: "The glowing platform beneath Shadowfang Island" },
      { after: "The ocean outside roared as the entire island powered up.", src: "/images/image4.jpeg", alt: "Shadowfang Island powering up at sea" },
    ],
    3: [
      { after: "The builders of Shadowfang Island were none other than the ancestors of Arthur Kingsley. For generations, Arthur’s family carried a mysterious symbol on their bodies. It was not an ordinary mark, but a sign that connected them to the island and its hidden secrets.", src: "/images/image5.jpeg", alt: "Arthur's ancestors and their mysterious symbol" },
      { after: "When the body was brought back, the old map that his father had carried was also recovered. That was how Arthur Kingsley came into possession of the map.", src: "/images/image6.png", alt: "Arthur's father's final journey and the recovered map" },
      { after: "Arthur became obsessed with finding the truth behind the symbol, the hidden island, and the strange connection between his family and Shadowfang Island.", src: "/images/image7.png", alt: "The mysterious connection between Arthur and Shadowfang Island" },
    ],
    4: [
      { after: "As he grew older, William became interested in science, survival skills, and exploring unknown places. He enjoyed solving puzzles and learning about hidden mysteries. Though he lived an ordinary life, he always felt that destiny had prepared something greater for him.", src: "/images/image9.jpeg", alt: "William working with a mechanical puzzle" },
      { after: "William was not just Arthur’s friend— he became like a brother to him.", src: "/images/image10.jpeg", alt: "Arthur and William walking together as friends" },
      { after: "That is why William Ashford became an important part of the journey to Shadowfang Island.", src: "/images/image11.jpeg", alt: "Arthur and William preparing to leave by boat" },
    ],
    5: [
      { after: "After Arthur Kingsley and William Ashford discovered Shadowfang Island.", src: "/images/image12.jpeg", alt: "A storm approaching a city" },
      { after: "What did they do after knowing the situation of the problem?", src: "/images/image13.jpeg", alt: "A craftsman forging a weapon" },
      { after: "Arthur chose to use this sword and practiced with it every day.", src: "/images/image14.jpeg", alt: "The Dragonflame Greatsword and Aetherion Staff" },
      { after: "They though it was of no use and they kept it aside. And started practicing with the two weapons.", src: "/images/image15.jpeg", alt: "Arthur with the Dragonflame Greatsword" },
      { after: "William trained himself too. He learned fighting skills, and tested every machine many times to make sure nothing would fail in battle.", src: "/images/image16.jpeg", alt: "A warrior holding the blue Aetherion Staff" },
      { after: "Thunder filled the air, and the sea became wild.", src: "/images/image17.jpeg", alt: "Arthur and William facing the approaching darkness" },
    ],
    6: [
      { before: true, src: "/images/image18.jpeg", alt: "Original chapter transition artwork" },
      { after: "Arthur Kingsley and William Ashford stood together. The sky was dark, thunder roared loudly, and the ground shook.", src: "/images/image19.jpeg", alt: "Arthur and William facing the Sentinel of Void" },
      { after: "Arthur and William combined their remaining power and threw the glowing Soul Reaver Scythe toward the Sentinel of Void.", src: "/images/image20.jpeg", alt: "The Soul Reaver Scythe striking the Sentinel of Void" },
      { after: "At last, the enemy was destroyed. Arthur and William had won the battle.", src: "/images/image21.jpeg", alt: "Arthur after the final battle" },
    ],
  },
};
